import fs from 'fs';
import path from 'path';
import { hashPassword } from '../server/db.js';

const DB_DIR = path.join(process.cwd(), 'data');
const DB_FILE = path.join(DB_DIR, 'minibid_db.json');

const superadminPass = hashPassword('admin123', 'seed_salt_superadmin');
const adminPass = hashPassword('admin123', 'seed_salt_admin');
const bidder1Pass = hashPassword('bidder123', 'seed_salt_bidder1');
const bidder2Pass = hashPassword('bidder123', 'seed_salt_bidder2');
const bidder3Pass = hashPassword('bidder123', 'seed_salt_bidder3');

const users = [
  {
    id: 'usr_superadmin',
    username: 'superadmin',
    email: 'superadmin@minibid.et',
    phone: '+251900000001',
    role: 'superadmin',
    wallet_balance: 0.0,
    status: 'active',
    email_verified: true,
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    password_hash: superadminPass.hash,
    salt: superadminPass.salt,
  },
  {
    id: 'usr_admin_ops',
    username: 'admin_ops',
    email: 'ops@minibid.et',
    phone: '+251900000002',
    role: 'admin',
    wallet_balance: 0.0,
    status: 'active',
    email_verified: true,
    created_at: new Date(Date.now() - 25 * 86400000).toISOString(),
    password_hash: adminPass.hash,
    salt: adminPass.salt,
  },
  {
    id: 'usr_aman',
    username: 'aman_bidder',
    email: 'aman@minibid.et',
    phone: '+251911223344',
    role: 'customer',
    wallet_balance: 0.0,
    status: 'active',
    email_verified: true,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    password_hash: bidder1Pass.hash,
    salt: bidder1Pass.salt,
    is_flagged: false,
    duplicate_txn_attempts: 0,
  },
  {
    id: 'usr_selam',
    username: 'selam_tech',
    email: 'selam@minibid.et',
    phone: '+251922334455',
    role: 'customer',
    wallet_balance: 0.0,
    status: 'active',
    email_verified: true,
    created_at: new Date(Date.now() - 10 * 86400000).toISOString(),
    password_hash: bidder2Pass.hash,
    salt: bidder2Pass.salt,
    is_flagged: false,
    duplicate_txn_attempts: 0,
  },
  {
    id: 'usr_dawit',
    username: 'dawit_crypto',
    email: 'dawit@minibid.et',
    phone: '+251933445566',
    role: 'customer',
    wallet_balance: 0.0,
    status: 'active',
    email_verified: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    password_hash: bidder3Pass.hash,
    salt: bidder3Pass.salt,
    is_flagged: false,
    duplicate_txn_attempts: 0,
  },
];

// Closed showcase auctions with rich historical bidder logs
const auctions = [
  {
    id: 'auc_closed_iphone16pro',
    title: 'Apple iPhone 16 Pro Max 256GB — Desert Titanium',
    category: 'Tech',
    description: 'Concluded flagship reverse auction. Won by lowest unique bidder @selam_tech at an astonishing 99.99% discount off market retail price.',
    image_url: 'https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=1000&q=80',
    start_price: 185000,
    bid_increment: 0.05,
    participation_fee: 40,
    internal_cost: 0,
    status: 'ended',
    start_time: new Date(Date.now() - 5 * 86400000).toISOString(),
    end_time: new Date(Date.now() - 1 * 86400000).toISOString(),
    total_bids: 8,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    winner_user_id: 'usr_selam',
    winner_username: 'selam_tech',
    winner_phone: '+251922334455',
    winner_email: 'selam@minibid.et',
    winning_bid_amount: 4.85,
    is_showcase: true,
  },
  {
    id: 'auc_closed_ps5pro',
    title: 'Sony PlayStation 5 Pro 2TB Digital Edition Console',
    category: 'Tech',
    description: 'Concluded next-gen console auction with Ray Tracing Pro. Won by lowest unique bidder @dawit_crypto.',
    image_url: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=1000&q=80',
    start_price: 85000,
    bid_increment: 0.05,
    participation_fee: 30,
    internal_cost: 0,
    status: 'ended',
    start_time: new Date(Date.now() - 8 * 86400000).toISOString(),
    end_time: new Date(Date.now() - 2 * 86400000).toISOString(),
    total_bids: 7,
    created_at: new Date(Date.now() - 8 * 86400000).toISOString(),
    winner_user_id: 'usr_dawit',
    winner_username: 'dawit_crypto',
    winner_phone: '+251933445566',
    winner_email: 'dawit@minibid.et',
    winning_bid_amount: 2.30,
    is_showcase: true,
  },
  {
    id: 'auc_closed_s24ultra',
    title: 'Samsung Galaxy S24 Ultra 512GB — Titanium Violet',
    category: 'Tech',
    description: 'Concluded reverse auction won by lowest unique bidder @aman_bidder for only 3.15 ETB.',
    image_url: 'https://images.unsplash.com/photo-1610945265064-0e34e5519bbf?auto=format&fit=crop&w=1000&q=80',
    start_price: 175000,
    bid_increment: 0.05,
    participation_fee: 35,
    internal_cost: 0,
    status: 'ended',
    start_time: new Date(Date.now() - 12 * 86400000).toISOString(),
    end_time: new Date(Date.now() - 3 * 86400000).toISOString(),
    total_bids: 8,
    created_at: new Date(Date.now() - 12 * 86400000).toISOString(),
    winner_user_id: 'usr_aman',
    winner_username: 'aman_bidder',
    winner_phone: '+251911223344',
    winner_email: 'aman@minibid.et',
    winning_bid_amount: 3.15,
    is_showcase: true,
  },
  {
    id: 'auc_closed_rolex',
    title: 'Rolex Submariner Date 41mm — Oystersteel & Cerachrom',
    category: 'Luxury',
    description: 'Concluded luxury Swiss timepiece auction with authentic box and warranty papers.',
    image_url: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=80',
    start_price: 1250000,
    bid_increment: 0.10,
    participation_fee: 150,
    internal_cost: 0,
    status: 'ended',
    start_time: new Date(Date.now() - 15 * 86400000).toISOString(),
    end_time: new Date(Date.now() - 4 * 86400000).toISOString(),
    total_bids: 6,
    created_at: new Date(Date.now() - 15 * 86400000).toISOString(),
    winner_user_id: 'usr_selam',
    winner_username: 'selam_tech',
    winner_phone: '+251922334455',
    winner_email: 'selam@minibid.et',
    winning_bid_amount: 8.70,
    is_showcase: true,
  },
];

// Rich Bidder Information for the closed auctions
const bids = [
  // iPhone 16 Pro Max bids
  {
    id: 'bid_cl_1',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 4.85,
    fee_paid: 40,
    created_at: new Date(Date.now() - 36 * 3600000).toISOString(),
    status: 'unique_lowest',
  },
  {
    id: 'bid_cl_2',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 5.10,
    fee_paid: 40,
    created_at: new Date(Date.now() - 38 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_3',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 6.25,
    fee_paid: 40,
    created_at: new Date(Date.now() - 42 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_4',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 6.25,
    fee_paid: 40,
    created_at: new Date(Date.now() - 45 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_5',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 7.40,
    fee_paid: 40,
    created_at: new Date(Date.now() - 50 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_6',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 8.90,
    fee_paid: 40,
    created_at: new Date(Date.now() - 55 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_7',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 9.55,
    fee_paid: 40,
    created_at: new Date(Date.now() - 60 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_8',
    auction_id: 'auc_closed_iphone16pro',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 9.55,
    fee_paid: 40,
    created_at: new Date(Date.now() - 65 * 3600000).toISOString(),
    status: 'not_unique',
  },

  // PS5 Pro bids
  {
    id: 'bid_cl_ps5_1',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 2.30,
    fee_paid: 30,
    created_at: new Date(Date.now() - 50 * 3600000).toISOString(),
    status: 'unique_lowest',
  },
  {
    id: 'bid_cl_ps5_2',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 3.15,
    fee_paid: 30,
    created_at: new Date(Date.now() - 55 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_ps5_3',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 4.20,
    fee_paid: 30,
    created_at: new Date(Date.now() - 60 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_ps5_4',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 4.20,
    fee_paid: 30,
    created_at: new Date(Date.now() - 62 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_ps5_5',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 5.65,
    fee_paid: 30,
    created_at: new Date(Date.now() - 70 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_ps5_6',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 6.80,
    fee_paid: 30,
    created_at: new Date(Date.now() - 75 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_ps5_7',
    auction_id: 'auc_closed_ps5pro',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 8.00,
    fee_paid: 30,
    created_at: new Date(Date.now() - 80 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },

  // S24 Ultra bids
  {
    id: 'bid_cl_s24_1',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 3.15,
    fee_paid: 35,
    created_at: new Date(Date.now() - 80 * 3600000).toISOString(),
    status: 'unique_lowest',
  },
  {
    id: 'bid_cl_s24_2',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 3.75,
    fee_paid: 35,
    created_at: new Date(Date.now() - 85 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_s24_3',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 4.50,
    fee_paid: 35,
    created_at: new Date(Date.now() - 90 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_s24_4',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 4.50,
    fee_paid: 35,
    created_at: new Date(Date.now() - 92 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_s24_5',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 5.95,
    fee_paid: 35,
    created_at: new Date(Date.now() - 100 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_s24_6',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 6.40,
    fee_paid: 35,
    created_at: new Date(Date.now() - 105 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_s24_7',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 7.85,
    fee_paid: 35,
    created_at: new Date(Date.now() - 110 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_s24_8',
    auction_id: 'auc_closed_s24ultra',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 7.85,
    fee_paid: 35,
    created_at: new Date(Date.now() - 115 * 3600000).toISOString(),
    status: 'not_unique',
  },

  // Rolex bids
  {
    id: 'bid_cl_rol_1',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 8.70,
    fee_paid: 150,
    created_at: new Date(Date.now() - 120 * 3600000).toISOString(),
    status: 'unique_lowest',
  },
  {
    id: 'bid_cl_rol_2',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 11.20,
    fee_paid: 150,
    created_at: new Date(Date.now() - 125 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_rol_3',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 14.50,
    fee_paid: 150,
    created_at: new Date(Date.now() - 130 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_rol_4',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_selam',
    username: 'selam_tech',
    bid_amount: 14.50,
    fee_paid: 150,
    created_at: new Date(Date.now() - 135 * 3600000).toISOString(),
    status: 'not_unique',
  },
  {
    id: 'bid_cl_rol_5',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_dawit',
    username: 'dawit_crypto',
    bid_amount: 18.00,
    fee_paid: 150,
    created_at: new Date(Date.now() - 140 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
  {
    id: 'bid_cl_rol_6',
    auction_id: 'auc_closed_rolex',
    user_id: 'usr_aman',
    username: 'aman_bidder',
    bid_amount: 22.40,
    fee_paid: 150,
    created_at: new Date(Date.now() - 145 * 3600000).toISOString(),
    status: 'unique_not_lowest',
  },
];

const freshCleanDb = {
  users,
  auctions,
  bids,
  deposits: [],
  financial_ledger: [],
  blocked_approval_attempts: [],
  idempotency_cache: {},
  admin_float_requests: [],
  transactions: [],
  notifications: [
    {
      id: `notif_welcome_${Date.now()}`,
      recipient_type: 'all',
      title: '🌟 MiniBid Platform Ready',
      message: 'Welcome to MiniBid Ethiopia, powered by Sunfyre General Trading! Explore concluded auctions and place bids on live listings.',
      type: 'info',
      created_at: new Date().toISOString(),
      read_by: [],
    },
  ],
  audit_logs: [
    {
      id: `aud_init_${Date.now()}`,
      actor_id: 'usr_superadmin',
      actor_username: 'superadmin',
      actor_role: 'superadmin',
      action: 'FINANCIAL_BASELINE_RESET',
      details: 'Super Admin financial ledger and deposit tables initialized to clean 0.00 ETB baseline. Concluded showcase auctions preserved with full bidder logs.',
      ip_reference: '127.0.0.1',
      created_at: new Date().toISOString(),
    },
  ],
};

fs.mkdirSync(DB_DIR, { recursive: true });
fs.writeFileSync(DB_FILE, JSON.stringify(freshCleanDb, null, 2), 'utf-8');
console.log('✅ Clean Database Baseline written successfully to', DB_FILE);
console.log('   - Active live auctions: 0 (All live auctions ended)');
console.log('   - Concluded showcase auctions with full bidder info: 4');
console.log('   - Deposits: 0 (Total Approved: 0.00 ETB)');
console.log('   - Financial Ledger: 0 entries');
console.log('   - Blocked Attempts: 0 entries');
console.log('   - User Wallets: Reset to 0.00 ETB');
